version: '3'

services:
  ansible:
    build:
      ./ansible
    volumes:
      - /Docker/ansible:/home/ansible/Automation
      - ~/.ssh:/home/ansible/.ssh
      - ~/.gitconfig:/home/ansible/.gitconfig
    stdin_open: true
    tty: true
    command: tail -f /dev/null
